python fullTissue.py -fullTissue -90
python fullTissue.py -fullTissue -85
python fullTissue.py -fullTissue -80
python fullTissue.py -fullTissue -75
python fullTissue.py -fullTissue -70
python fullTissue.py -fullTissue -65
python fullTissue.py -fullTissue -60
python fullTissue.py -fullTissue -55
python fullTissue.py -fullTissue -50
python fullTissue.py -fullTissue -45
python fullTissue.py -fullTissue -40
python fullTissue.py -fullTissue -35
python fullTissue.py -fullTissue -30
python fullTissue.py -fullTissue -25
python fullTissue.py -fullTissue -20
python fullTissue.py -fullTissue -15
python fullTissue.py -fullTissue -10
python fullTissue.py -fullTissue -5
python fullTissue.py -fullTissue 0
python fullTissue.py -fullTissue 5
python fullTissue.py -fullTissue 10
python fullTissue.py -fullTissue 15
python fullTissue.py -fullTissue 20
python fullTissue.py -fullTissue 25
